# Generated by Django 4.1.1 on 2022-12-10 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
